// The site's own wording – every line here can be changed in Admin → Tekster. `d` is the standard text (what shows
// until I write something else). Add a line here + use tx('key') in the page, and it appears in the admin list.
export interface TextItem { k: string; label: string; d: string; long?: boolean }
export interface TextGroup { title: string; items: TextItem[] }
export const TEXT_GROUPS: TextGroup[] = [
  { title: 'Figurer', items: [
    { k: 'figures.eyebrow', label: 'Lille tekst over tittelen', d: 'Hylla' },
    { k: 'figures.title', label: 'Tittel', d: 'Figurer' },
    { k: 'figures.hint', label: 'Hint', d: 'Trykk på en figur for å se den nærmere.' },
  ] },
  { title: 'Hjem', items: [
    { k: 'home.eyebrow', label: 'Lille tekst over hilsenen', d: 'Velkommen inn' },
    { k: 'home.hello', label: 'Hilsen (før navnet)', d: 'Hei, jeg er' },
    { k: 'home.name', label: 'Navnet', d: 'niben' },
    { k: 'home.intro', label: 'Innledning', d: 'Dette er rommet mitt på nettet – gitarene, bøkene jeg har lest, stedene jeg har reist og ting jeg har kodet.', long: true },
    { k: 'home.now', label: 'Overskrift «Akkurat nå»', d: 'Akkurat nå' },
    { k: 'home.tap', label: 'Hint i 3D-rommet', d: 'Trykk på noe i rommet, eller bruk menyen' },
    { k: 'home.made', label: 'Kreditt («Laget med …»)', d: 'Laget med' },
  ] },
  { title: 'Omvisning (første besøk i 3D)', items: [
    { k: 'tour.next', label: 'Knapp: neste', d: 'Neste' },
    { k: 'tour.done', label: 'Knapp: siste steg', d: 'Ferdig' },
    { k: 'tour.skip', label: 'Hopp over', d: 'Hopp over' },
    { k: 'tour.1.t', label: 'Steg 1: tittel', d: 'Velkommen inn' },
    { k: 'tour.1.b', label: 'Steg 1: tekst', d: 'Dette er rommet mitt. Alt i rommet er en del av siden – trykk på noe, så åpner det seg. Jeg tar deg en liten runde.', long: true },
    { k: 'tour.2.t', label: 'Steg 2: tittel (musikk)', d: 'Platespilleren' },
    { k: 'tour.2.b', label: 'Steg 2: tekst', d: 'Her hører jeg på musikk. Trykk på platespilleren for å se den ovenfra, på hylla for å bla i platene mine, og på iPoden for spillelistene.', long: true },
    { k: 'tour.3.t', label: 'Steg 3: tittel (gitar)', d: 'Gitarene' },
    { k: 'tour.3.b', label: 'Steg 3: tekst', d: 'Gitarene mine henger på veggen. Trykk på en for å lese om den.', long: true },
    { k: 'tour.4.t', label: 'Steg 4: tittel (bøker)', d: 'Bokhylla' },
    { k: 'tour.4.b', label: 'Steg 4: tekst', d: 'Bøkene jeg leser og har lest. Trykk på en rygg.', long: true },
    { k: 'tour.5.t', label: 'Steg 5: tittel (reiser)', d: 'Globusen' },
    { k: 'tour.5.b', label: 'Steg 5: tekst', d: 'Stedene jeg har vært. Velg et land for å se reisene og bildene.', long: true },
    { k: 'tour.6.t', label: 'Steg 6: tittel (kode)', d: 'Skrivebordet' },
    { k: 'tour.6.b', label: 'Steg 6: tekst', d: 'Det jeg koder på. Trykk på skjermen for å bla mellom prosjektene.', long: true },
    { k: 'tour.7.t', label: 'Steg 7: tittel (japansk)', d: 'Japansk' },
    { k: 'tour.7.b', label: 'Steg 7: tekst', d: 'Det jeg lærer akkurat nå: dagens ord, øving og anime.', long: true },
    { k: 'tour.8.t', label: 'Steg 8: tittel (om meg)', d: 'Om meg' },
    { k: 'tour.8.b', label: 'Steg 8: tekst', d: 'Bildet av meg henger på veggen. Der finner du mer om meg, og en gjestebok.', long: true },
    { k: 'tour.9.t', label: 'Steg 9: tittel (menyen)', d: 'Menyen og innstillinger' },
    { k: 'tour.9.b', label: 'Steg 9: tekst', d: 'Menyen tar deg dit du vil. Tannhjulet har språk, tema og grafikk – og der kan du bytte til den enkle versjonen eller se omvisningen igjen.', long: true },
    { k: 'tour.p1.t', label: 'Telefon, steg 1: tittel', d: 'Velkommen inn' },
    { k: 'tour.p1.b', label: 'Telefon, steg 1: tekst', d: 'Dette er rommet mitt. Trykk på ting i rommet, så åpner de seg – gitarer, bøker, globusen, skrivebordet.', long: true },
    { k: 'tour.p2.t', label: 'Telefon, steg 2: tittel', d: 'Menyen' },
    { k: 'tour.p2.b', label: 'Telefon, steg 2: tekst', d: 'Menyen ligger bak logoen oppe til venstre. I lytteplassen er det bare en liten bryter og knappene nederst.', long: true },
    { k: 'tour.p3.t', label: 'Telefon, steg 3: tittel', d: 'Innstillinger' },
    { k: 'tour.p3.b', label: 'Telefon, steg 3: tekst', d: 'Tannhjulet har språk, tema og grafikk. Der kan du også bytte til den enkle versjonen, som passer best på telefon.', long: true },
  ] },
  { title: 'Akkurat nå-kortene', items: [
    { k: 'now.listen', label: 'Overskrift: musikk', d: 'Hører på' },
    { k: 'now.listen.none', label: 'Når ingenting spilles', d: 'Ingenting akkurat nå.' },
    { k: 'now.daily', label: 'Overskrift: dagens plate', d: 'Dagens plate' },
    { k: 'now.read', label: 'Overskrift: bok', d: 'Leser' },
    { k: 'now.read.none', label: 'Når jeg ikke leser', d: 'Ingen bok i gang.' },
    { k: 'now.jp', label: 'Overskrift: japansk', d: 'Japansk' },
    { k: 'now.guitar', label: 'Overskrift: gitar', d: 'Øver på gitar' },
    { k: 'now.guitar.none', label: 'Når ingen låt er valgt', d: 'Ingen låt valgt.' },
    { k: 'now.games', label: 'Overskrift: spill', d: 'Spill' },
    { k: 'now.games.top', label: 'Liste: mest spilt', d: 'Mest spilt' },
  ] },
  { title: 'Reiser', items: [
    { k: 'travel.eyebrow', label: 'Lille tekst over tittelen', d: 'Reiser' },
    { k: 'travel.title', label: 'Tittel', d: 'Verden' },
    { k: 'travel.pick', label: 'Hint når ingen land er valgt', d: 'Velg et land for å se reisene og bildene.' },
    { k: 'travel.none', label: 'Når det ikke er noen reiser', d: 'Ingen reiser ennå.' },
    { k: 'travel.notyet', label: 'Land uten reiser', d: 'Ikke vært her ennå – kanskje neste tur?' },
  ] },
  { title: 'Bøker', items: [
    { k: 'books.eyebrow', label: 'Lille tekst over tittelen', d: 'Bøker' },
    { k: 'books.title', label: 'Tittel', d: 'Bokhylla' },
    { k: 'books.hint', label: 'Hint under tittelen', d: 'Trykk på en bok for å lese hva jeg synes.' },
    { k: 'books.none', label: 'Når det ikke er noen bøker', d: 'Ingen bøker ennå.' },
  ] },
  { title: 'Gitar', items: [
    { k: 'guitar.eyebrow', label: 'Lille tekst over tittelen', d: 'Gitar' },
    { k: 'guitar.title', label: 'Tittel (3D-rommet)', d: 'Gitarveggen' },
    { k: 'guitar.pageTitle', label: 'Tittel (enkel side)', d: 'Gitarene mine' },
    { k: 'guitar.hint', label: 'Hint', d: 'Trykk på en gitar for å se den og høre opptak.' },
    { k: 'guitar.none', label: 'Når det ikke er opptak', d: 'Ingen opptak ennå.' },
  ] },
  { title: 'Japansk', items: [
    { k: 'japan.eyebrow', label: 'Lille tekst over tittelen', d: '日本語' },
    { k: 'japan.title', label: 'Tittel', d: 'Japansk' },
    { k: 'japan.hint', label: 'Hint under tittelen', d: 'Det jeg lærer på jpdb – dagens ord ligger på bordet.' },
  ] },
  { title: 'Kode', items: [
    { k: 'code.eyebrow', label: 'Lille tekst over tittelen', d: 'Kode' },
    { k: 'code.title', label: 'Tittel', d: 'Prosjekter' },
    { k: 'code.hint', label: 'Hint under tittelen', d: 'Velg et prosjekt – det vises på skjermen.' },
  ] },
  { title: 'Gaming', items: [
    { k: 'gaming.eyebrow', label: 'Lille tekst over tittelen', d: 'Gaming' },
    { k: 'gaming.title', label: 'Tittel', d: 'Spillhjørnet' },
    { k: 'gaming.hint', label: 'Hint under tittelen', d: 'Hva jeg spiller på Steam – skjermen på pulten viser det også.' },
    { k: 'gaming.private', label: 'Når biblioteket er privat', d: 'Spillbiblioteket er privat på Steam.' },
    { k: 'gaming.how', label: 'Overskrift: slik spiller jeg', d: 'Slik spiller jeg' },
  ] },
  { title: 'Året', items: [
    { k: 'year.eyebrow', label: 'Lille tekst over tittelen', d: 'Året' },
    { k: 'year.title', label: 'Tittel', d: 'Mitt år' },
    { k: 'year.hint', label: 'Hint under tittelen', d: 'Samlet og klart til å deles som bilde.' },
    { k: 'year.empty', label: 'Når året er tomt', d: 'Året er ikke så langt – kom tilbake når det har skjedd mer.' },
  ] },
  { title: 'Om meg og øving', items: [
    { k: 'about.eyebrow', label: 'Om meg: lille tekst', d: 'Om meg' },
    { k: 'about.title', label: 'Om meg: tittel', d: 'Benjamin' },
    { k: 'practice.eyebrow', label: 'Øving: lille tekst', d: 'Øving' },
    { k: 'practice.title', label: 'Øving: tittel', d: 'Øvingshjørnet' },
    { k: 'practice.cal', label: 'Øvingskalender: forklaring', d: 'Kalenderen fylles når du øver her på siden – hver dag du gjør kort, får den en farge.', long: true },
  ] },
  { title: 'Oppdag', items: [
    { k: 'discover.eyebrow', label: 'Lille tekst over tittelen', d: 'Musikk' },
    { k: 'discover.title', label: 'Tittel', d: 'Oppdag' },
    { k: 'discover.hint', label: 'Hint (3D-panelet)', d: 'Album jeg anbefaler – og gode album du kanskje ikke har hørt.' },
    { k: 'discover.intro', label: 'Innledning', d: 'Album og låter jeg synes du bør høre, og forslag til gode album som ligner på det jeg har i samlingen.', long: true },
    { k: 'discover.add', label: 'Skjema (bare for meg)', d: 'Foreslå et album eller en låt' },
    { k: 'discover.picks', label: 'Overskrift: mine anbefalinger', d: 'Fra meg' },
    { k: 'discover.recs', label: 'Overskrift: forslag', d: 'Du kan like disse' },
    { k: 'discover.recs.hint', label: 'Forklaring til forslagene', d: 'Kjente album fra artister som ligner på dem jeg har mest av, men som ikke er i samlingen min.', long: true },
    { k: 'discover.none', label: 'Når det ikke er forslag ennå', d: 'Ingen forslag ennå.' },
  ] },
  { title: 'Nyhetsbrev', items: [
    { k: 'news.title', label: 'Tittel', d: 'Nye opptak på e-post' },
    { k: 'news.hint', label: 'Forklaring', d: 'Få en e-post når jeg legger ut et nytt gitaropptak – sjelden, og du kan melde deg av med ett klikk. Adressen brukes bare til dette.', long: true },
    { k: 'news.placeholder', label: 'Tekst i feltet', d: 'din@epost.no' },
    { k: 'news.button', label: 'Knapp', d: 'Meld meg på' },
    { k: 'news.thanks', label: 'Etter påmelding', d: 'Sjekk innboksen din og trykk på lenka i e-posten for å bekrefte. (Se i søppelposten hvis den ikke kommer.)', long: true },
  ] },
  { title: 'Gjestebok', items: [
    { k: 'guest.title', label: 'Tittel', d: 'Gjestebok' },
    { k: 'guest.note', label: 'Under skjemaet', d: 'Hilsenen vises etter at jeg har lest den.' },
    { k: 'guest.thanks', label: 'Etter innsending', d: 'Takk for hilsenen! Den dukker opp her så snart jeg har lest den.', long: true },
    { k: 'guest.none', label: 'Når ingen har skrevet', d: 'Ingen hilsener ennå – bli den første.' },
  ] },
]
export const TEXT_DEFAULTS: Record<string, string> = Object.fromEntries(TEXT_GROUPS.flatMap((g) => g.items.map((i): [string, string] => [i.k, i.d])))
