// The hobby modules a room can add. Every kind is data: a name, a symbol, a colour, the fields of one entry and how the entries
// are shown. Adding a hobby = adding a line here (the server only keeps what the page sends, so nothing else needs to change).
export type FieldKind = 'text' | 'longtext' | 'number' | 'date' | 'select' | 'rating' | 'url' | 'image' | 'hidden'
export interface Field { k: string; label: string; kind: FieldKind; options?: string[]; unit?: string }
/** How the entries look: a card grid, a dated log with numbers and a chart, or a checklist with progress. */
export type Layout = 'cards' | 'log' | 'checklist'
/** Public services (no key) that can look up what you type: film posters, series, podcasts, recipes, species, countries. */
export type LookupSource = 'film' | 'serie' | 'podkast' | 'matrett' | 'art' | 'land' | 'sted'
export const CATEGORIES = ['Se, lytt og spill', 'Mat og drikke', 'Skap og bygg', 'Natur og dyr', 'Kropp og friluft', 'Hode og ord', 'Planlegg']
export interface ModuleKind {
  id: string; name: string; icon: string /* a name in lib/icons.ts */; color: string; blurb: string
  cat: string // the group it belongs to in the list of modules (CATEGORIES)
  lookup?: LookupSource // a service that can fill in an entry from a title (poster, link …)
  layout: Layout // (what stands in the room is its model in three/moduleModels.ts)
  fields: Field[] // the first one is the title of the entry
  stat?: { field: string; label: string; op: 'sum' | 'avg' | 'max' } // log: the number that is added up
  workout?: boolean // entries are workouts: pace, a weekly goal and a GPX import
  live?: 'chess' | 'apod' // an account on a public service whose numbers are shown on top
}

const t = (k: string, label: string): Field => ({ k, label, kind: 'text' })
const note = (): Field => ({ k: 'note', label: 'Notat', kind: 'longtext' })
const date = (label = 'Dato'): Field => ({ k: 'date', label, kind: 'date' })
const num = (k: string, label: string, unit?: string): Field => ({ k, label, kind: 'number', unit })
const stars = (): Field => ({ k: 'rating', label: 'Vurdering', kind: 'rating' })
const pick = (k: string, label: string, options: string[]): Field => ({ k, label, kind: 'select', options })
const link = (): Field => ({ k: 'url', label: 'Lenke', kind: 'url' })
const img = (): Field => ({ k: 'img', label: 'Bilde', kind: 'image' }) // (uploaded from the device, or a web address)
const STATUS = ['Vil prøve', 'Holder på', 'Ferdig']

export const CATALOG: ModuleKind[] = [
  // ── watched, played, made: cards ──
  { id: 'restauranter', name: 'Restauranter', icon: 'UtensilsCrossed', color: '#d9480f', blurb: 'Steder du har spist, med vurdering og kart', cat: 'Mat og drikke', lookup: 'sted', layout: 'cards', fields: [t('t', 'Sted'), pick('kat', 'Kjøkken', ['Norsk', 'Italiensk', 'Asiatisk', 'Pizza', 'Burger', 'Kafé og bakeri', 'Bar', 'Annet']), stars(), pick('pris', 'Pris', ['$', '$$', '$$$', '$$$$']), t('adresse', 'Adresse'), date('Besøkt'), note(), link(), img()] },
  { id: 'filmer', name: 'Filmer', icon: 'Clapperboard', color: '#e5484d', blurb: 'Filmer du har sett og vil se', cat: 'Se, lytt og spill', lookup: 'film', layout: 'cards', fields: [t('t', 'Tittel'), pick('kat', 'Sjanger', ['Drama', 'Komedie', 'Action', 'Skrekk', 'Sci-fi', 'Dokumentar', 'Animasjon', 'Annet']), pick('status', 'Status', ['Vil se', 'Sett']), stars(), date('Sett'), note(), img()] },
  { id: 'serier', name: 'Serier', icon: 'Tv', color: '#7c5cff', blurb: 'Hvor langt du er kommet', cat: 'Se, lytt og spill', lookup: 'serie', layout: 'cards', fields: [t('t', 'Tittel'), pick('kat', 'Sjanger', ['Drama', 'Komedie', 'Krim', 'Sci-fi', 'Dokumentar', 'Animasjon', 'Annet']), pick('status', 'Status', ['Vil se', 'Ser nå', 'Ferdig', 'Droppet']), t('episode', 'Sesong / episode'), stars(), note(), img()] },
  { id: 'brettspill', name: 'Brettspill', icon: 'Dice5', color: '#f5a524', blurb: 'Samlingen og hvem som vant', cat: 'Se, lytt og spill', layout: 'cards', fields: [t('t', 'Spill'), pick('kat', 'Type', ['Strategi', 'Kortspill', 'Familie', 'Samarbeid', 'Selskapsspill', 'Annet']), num('spillere', 'Spillere'), num('min', 'Minutter', 'min'), stars(), note(), img()] },
  { id: 'oppskrifter', name: 'Oppskrifter', icon: 'ChefHat', color: '#f76b15', blurb: 'Det du har laget og vil lage igjen', cat: 'Mat og drikke', lookup: 'matrett', layout: 'cards', fields: [t('t', 'Rett'), pick('kat', 'Kategori', ['Frokost', 'Middag', 'Dessert', 'Snacks', 'Suppe', 'Bakst', 'Drikke']), pick('status', 'Status', ['Vil lage', 'Laget', 'Favoritt']), num('min', 'Tid', 'min'), stars(), { k: 'oppskrift', label: 'Oppskrift', kind: 'longtext' }, img()] },
  { id: 'baking', name: 'Baking', icon: 'Croissant', color: '#c98a4b', blurb: 'Brød, kaker og hvordan det gikk', cat: 'Mat og drikke', lookup: 'matrett', layout: 'cards', fields: [t('t', 'Hva'), pick('kat', 'Kategori', ['Brød', 'Kaker', 'Boller', 'Kjeks', 'Paier', 'Annet']), date(), stars(), note(), img()] },
  { id: 'kaffe', name: 'Kaffe og te', icon: 'Coffee', color: '#8b5e3c', blurb: 'Bønner, bladene og smaken', cat: 'Mat og drikke', layout: 'cards', fields: [t('t', 'Navn'), t('opphav', 'Opphav'), pick('type', 'Type', ['Kaffe', 'Te', 'Annet']), stars(), note()] },
  { id: 'vin', name: 'Vin og øl', icon: 'Wine', color: '#a02850', blurb: 'Smaksnotater og favoritter', cat: 'Mat og drikke', layout: 'cards', fields: [t('t', 'Navn'), t('produsent', 'Produsent'), pick('type', 'Type', ['Rødvin', 'Hvitvin', 'Musserende', 'Øl', 'Annet']), stars(), note()] },
  { id: 'planter', name: 'Planter', icon: 'Sprout', color: '#2fa84f', blurb: 'Hva som står hvor og når det ble vannet', cat: 'Natur og dyr', lookup: 'art', layout: 'cards', fields: [t('t', 'Plante'), pick('kat', 'Type', ['Stueplante', 'Urt', 'Kaktus og sukkulent', 'Blomst', 'Tre', 'Annet']), t('sted', 'Står i'), date('Sist vannet'), num('dager', 'Vann hver', 'dager'), note(), img()] },
  { id: 'akvarium', name: 'Akvarium', icon: 'Fish', color: '#2b9fd8', blurb: 'Fisk, planter og vannprøver', cat: 'Natur og dyr', layout: 'cards', fields: [t('t', 'Hva'), num('antall', 'Antall'), date('Siden'), note(), img()] },
  { id: 'kjaledyr', name: 'Kjæledyr', icon: 'PawPrint', color: '#e07b53', blurb: 'Gutta og jentene i huset', cat: 'Natur og dyr', layout: 'cards', fields: [t('t', 'Navn'), t('art', 'Art / rase'), date('Født'), note(), img()] },
  { id: 'retro', name: 'Retro-samling', icon: 'Gamepad2', color: '#5c6bc0', blurb: 'Konsoller, spill og kassetter', cat: 'Se, lytt og spill', layout: 'cards', fields: [t('t', 'Tittel'), pick('kat', 'Type', ['Konsoll', 'Spill', 'Tilbehør', 'Datamaskin', 'Annet']), t('system', 'System'), pick('stand', 'Stand', ['Ny', 'God', 'Slitt', 'Mangler boks']), note(), img()] },
  { id: 'lego', name: 'LEGO', icon: 'Blocks', color: '#f0c020', blurb: 'Sett du har bygget', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Sett'), t('nr', 'Nummer'), pick('status', 'Status', ['Uåpnet', 'Bygger', 'Ferdig']), note(), img()] },
  { id: 'modell', name: 'Modellbygging', icon: 'Plane', color: '#6b7a8f', blurb: 'Fly, skip og diorama', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Modell'), t('skala', 'Skala'), pick('status', 'Status', STATUS), note(), img()] },
  { id: 'kunst', name: 'Tegning og maling', icon: 'Palette', color: '#d6409f', blurb: 'Verkene dine', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Tittel'), pick('kat', 'Sjanger', ['Akvarell', 'Olje', 'Blyant', 'Digitalt', 'Skisse', 'Annet']), t('teknikk', 'Teknikk'), date(), note(), img()] },
  { id: 'foto', name: 'Foto', icon: 'Camera', color: '#4a5568', blurb: 'Bildene du er stolt av', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Tittel'), pick('kat', 'Sjanger', ['Landskap', 'Portrett', 'Gate', 'Natur', 'Arkitektur', 'Annet']), t('sted', 'Sted'), date(), note(), img()] },
  { id: 'strikking', name: 'Strikking og håndarbeid', icon: 'Scissors', color: '#e5658a', blurb: 'Prosjekter på pinnene', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Prosjekt'), pick('kat', 'Type', ['Genser', 'Lue', 'Sokker', 'Teppe', 'Annet']), t('garn', 'Garn'), pick('status', 'Status', STATUS), note(), img()] },
  { id: 'diy', name: 'Verksted', icon: 'Wrench', color: '#718096', blurb: 'Ting du bygger og fikser', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Prosjekt'), pick('kat', 'Kategori', ['Tre', 'Elektronikk', 'Hjem', 'Sykkel', 'Bil', 'Annet']), pick('status', 'Status', STATUS), t('materialer', 'Materialer'), note(), img()] },
  { id: 'piano', name: 'Piano og instrumenter', icon: 'Piano', color: '#2d3748', blurb: 'Repertoaret ditt', cat: 'Se, lytt og spill', layout: 'cards', fields: [t('t', 'Stykke'), pick('kat', 'Sjanger', ['Klassisk', 'Jazz', 'Pop', 'Film og spill', 'Rock', 'Annet']), t('komponist', 'Av'), pick('status', 'Status', ['Lærer', 'Kan det', 'Kan det utenat']), note()] },
  { id: 'dans', name: 'Dans', icon: 'Music4', color: '#ec4899', blurb: 'Koreografier og stiler', cat: 'Se, lytt og spill', layout: 'cards', fields: [t('t', 'Dans'), pick('kat', 'Sjanger', ['Salsa', 'Swing', 'Hiphop', 'Ballett', 'Vals', 'Annet']), t('stil', 'Stil'), pick('status', 'Status', ['Lærer', 'Sitter']), link(), note()] },
  { id: 'podkaster', name: 'Podkaster', icon: 'Mic', color: '#9333ea', blurb: 'Det du hører på', cat: 'Se, lytt og spill', lookup: 'podkast', layout: 'cards', fields: [t('t', 'Program'), pick('kat', 'Tema', ['Nyheter', 'Komedie', 'Krim', 'Læring', 'Sport', 'Teknologi', 'Historie', 'Annet']), t('episode', 'Siste episode'), stars(), link(), note()] },
  { id: 'samling', name: 'Samlerobjekter', icon: 'Gem', color: '#0ea5a5', blurb: 'Kort, mynter, frimerker …', cat: 'Skap og bygg', layout: 'cards', fields: [t('t', 'Gjenstand'), pick('kat', 'Type', ['Kort', 'Mynter', 'Frimerker', 'Figurer', 'Plakater', 'Annet']), t('serie', 'Serie / år'), pick('stand', 'Stand', ['Mint', 'God', 'Slitt']), note(), img()] },
  { id: 'bokmerker', name: 'Bokmerker', icon: 'Bookmark', color: '#3b82f6', blurb: 'Sider du vil huske', cat: 'Hode og ord', layout: 'cards', fields: [t('t', 'Tittel'), pick('kat', 'Kategori', ['Artikkel', 'Verktøy', 'Video', 'Inspirasjon', 'Annet']), link(), t('tema', 'Tema'), note()] },
  { id: 'fugler', name: 'Fuglekikking', icon: 'Bird', color: '#16a34a', blurb: 'Arter du har sett', cat: 'Natur og dyr', lookup: 'art', layout: 'cards', fields: [t('t', 'Art'), pick('kat', 'Gruppe', ['Spurvefugl', 'Rovfugl', 'Vannfugl', 'Vadefugl', 'Ugle', 'Annet']), date('Sett'), t('sted', 'Sted'), note(), img()] },
  { id: 'astronomi', name: 'Stjernekikking', icon: 'Telescope', color: '#4338ca', blurb: 'Hva du har sett på himmelen', cat: 'Natur og dyr', live: 'apod', layout: 'cards', fields: [t('t', 'Objekt'), pick('kat', 'Type', ['Planet', 'Måne', 'Stjerne', 'Galakse', 'Nebula', 'Satellitt', 'Annet']), date(), t('sted', 'Sted'), note(), img()] },
  // ── numbers over time: log ──
  { id: 'trening', name: 'Trening', icon: 'Medal', color: '#fc4c02', blurb: 'Økter, tempo, rekorder og ukemål – importer en GPX-fil og se ruten', cat: 'Kropp og friluft', layout: 'log', workout: true, stat: { field: 'km', label: 'km til sammen', op: 'sum' },
    fields: [date(), pick('kat', 'Type', ['Løping', 'Sykling', 'Svømming', 'Gåtur', 'Fottur', 'Ski', 'Styrke', 'Yoga', 'Annet']), t('t', 'Tittel'), num('km', 'Distanse', 'km'), num('min', 'Tid', 'min'), num('hm', 'Høydemeter', 'm'), num('puls', 'Snittpuls', 'slag'), pick('foles', 'Følelse', ['Lett', 'Fin', 'Tung', 'Helt tom']), note(), { k: 'route', label: 'Rute', kind: 'hidden' }] },
  { id: 'lop', name: 'Løping', icon: 'Footprints', color: '#ef4444', blurb: 'Turer, tider og kilometer', cat: 'Kropp og friluft', layout: 'log', stat: { field: 'km', label: 'km til sammen', op: 'sum' }, fields: [date(), num('km', 'Distanse', 'km'), num('min', 'Tid', 'min'), note()] },
  { id: 'sykling', name: 'Sykling', icon: 'Bike', color: '#f97316', blurb: 'Turer og høydemeter', cat: 'Kropp og friluft', layout: 'log', stat: { field: 'km', label: 'km til sammen', op: 'sum' }, fields: [date(), num('km', 'Distanse', 'km'), num('hm', 'Høydemeter', 'm'), note()] },
  { id: 'styrke', name: 'Styrketrening', icon: 'Dumbbell', color: '#334155', blurb: 'Økter og rekorder', cat: 'Kropp og friluft', layout: 'log', stat: { field: 'kg', label: 'kg tyngste', op: 'max' }, fields: [date(), t('ovelse', 'Øvelse'), num('kg', 'Vekt', 'kg'), num('reps', 'Repetisjoner'), note()] },
  { id: 'svomming', name: 'Svømming', icon: 'Waves', color: '#0284c7', blurb: 'Lengder og tid i vannet', cat: 'Kropp og friluft', layout: 'log', stat: { field: 'meter', label: 'meter til sammen', op: 'sum' }, fields: [date(), num('meter', 'Distanse', 'm'), num('min', 'Tid', 'min'), note()] },
  { id: 'tur', name: 'Fjellturer', icon: 'Mountain', color: '#65a30d', blurb: 'Topper du har stått på', cat: 'Kropp og friluft', lookup: 'sted', layout: 'log', stat: { field: 'hm', label: 'høydemeter', op: 'sum' }, fields: [date(), t('t', 'Tur'), num('km', 'Distanse', 'km'), num('hm', 'Høydemeter', 'm'), note()] },
  { id: 'fiske', name: 'Fiske', icon: 'Fish', color: '#0d9488', blurb: 'Fangster og steder', cat: 'Kropp og friluft', layout: 'log', stat: { field: 'kg', label: 'kg største', op: 'max' }, fields: [date(), t('art', 'Art'), num('kg', 'Vekt', 'kg'), t('sted', 'Sted'), note()] },
  { id: 'camping', name: 'Camping', icon: 'Tent', color: '#ca8a04', blurb: 'Netter ute', cat: 'Kropp og friluft', lookup: 'sted', layout: 'log', stat: { field: 'netter', label: 'netter ute', op: 'sum' }, fields: [date(), t('sted', 'Sted'), num('netter', 'Netter'), note()] },
  { id: 'sjakk', name: 'Sjakk', icon: 'Crown', color: '#475569', blurb: 'Rating fra chess.com eller lichess, og partiene dine', cat: 'Hode og ord', layout: 'log', live: 'chess', stat: { field: 'rating', label: 'høyeste rating', op: 'max' }, fields: [date(), t('motstander', 'Motstander'), pick('res', 'Resultat', ['Seier', 'Remis', 'Tap']), num('rating', 'Rating'), note()] },
  { id: 'skriving', name: 'Skriving', icon: 'PenLine', color: '#b45309', blurb: 'Ord skrevet, dag for dag', cat: 'Hode og ord', layout: 'log', stat: { field: 'ord', label: 'ord til sammen', op: 'sum' }, fields: [date(), t('t', 'Prosjekt'), num('ord', 'Ord'), note()] },
  { id: 'sprak', name: 'Språklæring', icon: 'Languages', color: '#0891b2', blurb: 'Minutter øvd per dag', cat: 'Hode og ord', layout: 'log', stat: { field: 'min', label: 'minutter til sammen', op: 'sum' }, fields: [date(), t('sprak', 'Språk'), num('min', 'Tid', 'min'), note()] },
  { id: 'meditasjon', name: 'Meditasjon', icon: 'Flower2', color: '#8b5cf6', blurb: 'Rolige minutter', cat: 'Kropp og friluft', layout: 'log', stat: { field: 'min', label: 'minutter til sammen', op: 'sum' }, fields: [date(), num('min', 'Tid', 'min'), note()] },
  { id: 'dagbok', name: 'Dagbok', icon: 'NotebookPen', color: '#64748b', blurb: 'Én linje om dagen', cat: 'Hode og ord', layout: 'log', fields: [date(), t('t', 'Overskrift'), { k: 'tekst', label: 'Tekst', kind: 'longtext' }] },
  { id: 'bil', name: 'Bil og motorsykkel', icon: 'Car', color: '#dc2626', blurb: 'Kilometer, service og turer', cat: 'Planlegg', layout: 'log', stat: { field: 'km', label: 'km til sammen', op: 'sum' }, fields: [date(), t('t', 'Hva'), num('km', 'Kilometer', 'km'), num('kr', 'Kostnad', 'kr'), note()] },
  // ── to do, to get, to try: checklist ──
  { id: 'onskeliste', name: 'Ønskeliste', icon: 'Gift', color: '#e11d48', blurb: 'Det du ønsker deg', cat: 'Planlegg', layout: 'checklist', fields: [t('t', 'Ønske'), pick('kat', 'Kategori', ['Teknologi', 'Klær', 'Hjem', 'Opplevelse', 'Annet']), num('pris', 'Pris', 'kr'), link(), note()] },
  { id: 'bucket', name: 'Bucket list', icon: 'Target', color: '#0ea5e9', blurb: 'Ting å gjøre før du dør', cat: 'Planlegg', layout: 'checklist', fields: [t('t', 'Mål'), pick('kat', 'Kategori', ['Reise', 'Opplevelse', 'Lære', 'Prestasjon', 'Annet']), date('Når'), note()] },
  { id: 'hage', name: 'Hage og dyrking', icon: 'Shovel', color: '#4d7c0f', blurb: 'Sesongens gjøremål', cat: 'Natur og dyr', layout: 'checklist', fields: [t('t', 'Oppgave'), pick('kat', 'Kategori', ['Så', 'Plante', 'Beskjære', 'Høste', 'Vedlikehold']), date('Innen'), note()] },
  { id: 'reisemal', name: 'Reisemål', icon: 'Luggage', color: '#0f766e', blurb: 'Steder du vil til', cat: 'Planlegg', lookup: 'land', layout: 'checklist', fields: [t('t', 'Sted'), pick('kat', 'Type', ['Storby', 'Natur', 'Strand', 'Fjell', 'Kultur', 'Annet']), t('land', 'Land'), date('Når'), note()] },
]

export const kindOf = (id: string | undefined): ModuleKind | undefined => CATALOG.find((k) => k.id === id)
